[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Chris Lucas <chris@chrisjlucas.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutate = "0.3"
